name: YT build
on:
  push:
    branches: [ "Vip" ]
  pull_request:
    branches: [ "Vip" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run code
        run: |
          chmod 777 install.sh
          . install.sh
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: Apks
          path: apk/*
