name: YT-AT
on: 
  workflow_dispatch:
    inputs:
      VERSION:
        description: '17-32-39 => 17.32.39 is the YouTube version that revanced supports tool'
        required: true
        default: '17-32-39'
      DEVICE:
        description: 'Select device'
        required: true
        default: 'arm64-v8a'
        type: choice
        options:
          - armeabi-v7a
          - arm64-v8a
          - x86
          - x86_64
      LANGUAGE:
        description: 'Add language revanced mod'
        required: true
        default: 'Default'
        type: choice
        options:
          - 'Default'
          - 'vi-VN'
      FEATURE:
        description: 'Turn off the feature, Add spaces to distinguish each feature'
        required: true
        default: 'always-autorepeat disable-create-button hide-autoplay-button hide-shorts-button'
      ICONS:
        description: 'Original icon & Name'
        required: false
        type: boolean
        default: true
      AMOLED:
        description: 'Dark Theme'
        required: false
        type: boolean
        default: true
      OPTIMIZATION:
        description: 'Video loaded speed'
        required: false
        type: boolean
        default: true
      TYPE:
        description: 'Sign in microg (No Root)'
        required: false
        type: boolean
        default: true
      ROUND:
        description: 'Pip rounded (root)'
        required: false
        type: boolean
        default: true
jobs:
  build:
    name: 'Auto Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run code
        env:
          VERSION: ${{ inputs.VERSION }}
          DEVICE: ${{ inputs.DEVICE }}
          ICONS: ${{ inputs.ICONS }}
          OPTIMIZATION: ${{ inputs.OPTIMIZATION }}
          AMOLED: ${{ inputs.AMOLED }}
          FEATURE: ${{ inputs.FEATURE }}
          ROUND: ${{ inputs.ROUND }}
          TYPE: ${{ inputs.TYPE }}
          LANGUAGE: ${{ inputs.LANGUAGE }}

        run: |
          SVision="17.32.35"
          chmod -R 777 Tools/*
          chmod 777 install.sh
          . install.sh
      - name: Upload json
        uses: softprops/action-gh-release@v1
        with:
          name: Update
          tag_name: Up
          files: Up*.json
          prerelease: true
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: YouTube
          path: Up/*
      - name: Upload File
        uses: softprops/action-gh-release@v1
        with:
          name: YT-AT
          tag_name: Download
          files: Up/*
