name: YT build Main
on: 
  label:
    types:
      - edited
  push:
    branches: 
      - Vip
  workflow_dispatch:
    inputs:
      PHIEN_BAN:
        description: '17-32-35 => 17.32.35 is the YouTube version that revanced supports tool'
        required: true
        default: '17-32-35'
      DEVICE:
        description: 'Select device'
        required: true
        default: 'arm64-v8a'
        type: choice
        options:
          - armeabi-v7a
          - arm64-v8a
          - x86
          - x86_64
      ICONS:
        description: 'Original icon'
        required: false
        type: boolean
        default: true
      AMOLED:
        description: 'Dark Theme'
        required: false
        type: boolean
        default: true
      OPTIMIZATION:
        description: 'Increase video download speed '
        required: false
        type: boolean
        default: true
      TYPE:
        description: 'Sign in with microg (No Root)'
        required: false
        type: boolean
        default: true
      ROUND:
        description: 'Window rounded feature is only for root'
        required: false
        type: boolean
        default: true
      ICONS:
        description: 'Turn off the feature. To distinguish, add a space, And do not enter a new line'
        required: true
        default: 'hide-shorts-button always-autorepeat hide-autoplay-button disable-create-button'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run code
        run: |
          chmod 777 install.sh
          #. install.sh
      - name: Upload json
        uses: softprops/action-gh-release@v1
        with:
          name: Update
          tag_name: Up
          files: Up*.json
          prerelease: true
      - name: Upload File
        uses: softprops/action-gh-release@v1
        with:
          name: YT-AT
          tag_name: Download
          files: Up/*
